module.exports = {
  apps: [
    // Pet Insurance
    {
      name: 'pet-insurance',
      cwd: './apps/pet-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/pet-insurance-error.log',
      out_file: './logs/pet-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Disability Insurance
    {
      name: 'disability-insurance',
      cwd: './apps/disability-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: './logs/disability-insurance-error.log',
      out_file: './logs/disability-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Cyber Insurance
    {
      name: 'cyber-insurance',
      cwd: './apps/cyber-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: './logs/cyber-insurance-error.log',
      out_file: './logs/cyber-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Travel Insurance
    {
      name: 'travel-insurance',
      cwd: './apps/travel-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: './logs/travel-insurance-error.log',
      out_file: './logs/travel-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Umbrella Insurance
    {
      name: 'umbrella-insurance',
      cwd: './apps/umbrella-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      error_file: './logs/umbrella-insurance-error.log',
      out_file: './logs/umbrella-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Motorcycle Insurance
    {
      name: 'motorcycle-insurance',
      cwd: './apps/motorcycle-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      error_file: './logs/motorcycle-insurance-error.log',
      out_file: './logs/motorcycle-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // SR-22 Insurance
    {
      name: 'sr22-insurance',
      cwd: './apps/sr22-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
      },
      error_file: './logs/sr22-insurance-error.log',
      out_file: './logs/sr22-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Wedding Insurance
    {
      name: 'wedding-insurance',
      cwd: './apps/wedding-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3008,
      },
      error_file: './logs/wedding-insurance-error.log',
      out_file: './logs/wedding-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Drone Insurance
    {
      name: 'drone-insurance',
      cwd: './apps/drone-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3009,
      },
      error_file: './logs/drone-insurance-error.log',
      out_file: './logs/drone-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    // Landlord Insurance
    {
      name: 'landlord-insurance',
      cwd: './apps/landlord-insurance-compare',
      script: 'npm',
      args: 'start',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3010,
      },
      error_file: './logs/landlord-insurance-error.log',
      out_file: './logs/landlord-insurance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
  ],
};
