import { Navbar, Footer } from '@traffic2u/ui';
import { Sparkles } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar
        logo={<Sparkles className="h-6 w-6 text-blue-600" />}
        appName="CodeSnap"
      />

      <div className="flex-1 bg-white py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
          <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>
          <div className="prose prose-blue max-w-none">
            <p className="text-gray-600 mb-6">Last updated: {new Date().toLocaleDateString()}</p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700 mb-4">
                By accessing and using CodeSnap ("the Service"), you accept and agree to be bound by the terms
                and provisions of this agreement. If you do not agree to these Terms of Service, please do not
                use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-700 mb-4">
                CodeSnap provides an AI-powered service that converts UI screenshots into production-ready code.
                The Service uses advanced machine learning models to analyze images and generate corresponding
                code in various frameworks including React, Vue, Svelte, and HTML/CSS.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Accounts</h2>
              <p className="text-gray-700 mb-4">
                To use certain features of the Service, you must register for an account. You agree to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Provide accurate, current, and complete information during registration</li>
                <li>Maintain and update your information to keep it accurate and current</li>
                <li>Maintain the security of your password and account</li>
                <li>Notify us immediately of any unauthorized use of your account</li>
                <li>Accept responsibility for all activities that occur under your account</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Subscription and Payment</h2>
              <p className="text-gray-700 mb-4">
                CodeSnap offers both free and paid subscription plans. By subscribing to a paid plan:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>You agree to pay the subscription fees as described on our pricing page</li>
                <li>Payments are processed securely through Stripe</li>
                <li>Subscriptions automatically renew unless canceled before the renewal date</li>
                <li>Refunds are provided according to our refund policy (7-day money-back guarantee)</li>
                <li>We reserve the right to change pricing with 30 days notice</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Usage Limits</h2>
              <p className="text-gray-700 mb-4">
                Each subscription plan includes specific usage limits (number of conversions per month).
                Exceeding these limits may result in:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Temporary suspension of service until the next billing cycle</li>
                <li>Upgrade requirement to a higher-tier plan</li>
                <li>Additional charges for overage (if applicable to your plan)</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Intellectual Property</h2>
              <p className="text-gray-700 mb-4">
                The code generated by CodeSnap is owned by you. However, you acknowledge that:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>The CodeSnap service, platform, and technology remain our property</li>
                <li>You may use generated code for any purpose, including commercial projects</li>
                <li>We retain the right to use anonymized usage data to improve the Service</li>
                <li>You grant us a license to process uploaded screenshots solely to provide the Service</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Prohibited Uses</h2>
              <p className="text-gray-700 mb-4">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 mb-4 space-y-2">
                <li>Violate any laws or regulations</li>
                <li>Infringe on intellectual property rights of others</li>
                <li>Upload malicious content or malware</li>
                <li>Attempt to reverse engineer or circumvent the Service</li>
                <li>Resell or redistribute generated code as a competing service</li>
                <li>Use automated systems to abuse the Service</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Disclaimer of Warranties</h2>
              <p className="text-gray-700 mb-4">
                THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. While we strive for accuracy,
                we do not guarantee that generated code will be error-free or suitable for all purposes.
                You are responsible for testing and validating generated code before use in production.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Limitation of Liability</h2>
              <p className="text-gray-700 mb-4">
                To the maximum extent permitted by law, CodeSnap shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages resulting from your use of the Service.
                Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Termination</h2>
              <p className="text-gray-700 mb-4">
                We reserve the right to suspend or terminate your account if you violate these Terms.
                You may cancel your subscription at any time through your account settings.
                Upon termination, your access to the Service will cease immediately.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Changes to Terms</h2>
              <p className="text-gray-700 mb-4">
                We reserve the right to modify these Terms at any time. We will notify users of significant
                changes via email. Continued use of the Service after changes constitutes acceptance of the
                modified Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Contact Information</h2>
              <p className="text-gray-700 mb-4">
                If you have questions about these Terms, please contact us at:
              </p>
              <p className="text-gray-700">
                Email: legal@codesnap.com<br />
                Address: [Your Business Address]
              </p>
            </section>
          </div>
        </div>
      </div>

      <Footer appName="CodeSnap" />
    </div>
  );
}
